server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: finance-reservation-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance_reservation_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pingpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[hibernate.jdbc.lob.non_contextual_creation]": true
        generate_statistics: true
        format_sql: true

logging:
  level:
    org.hibernate.stat: DEBUG